version: '3'

services:
  hr-portal:
    build:
      context: /Users/sovathapann/Gig_Work/hr-webportal/apphr
      # dockerfile: Dockerfile
    ports:
      - "28999:28999"
    networks:
      - webnet

  nginx:
    build: ./nginx
    container_name: nginx-server
    networks:
      - webnet

  apache:
    build: ./apache
    container_name: apache-server
    networks:
      - webnet


  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/nginx_custom.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nginx
      - apache
    networks:
      - webnet

networks:
  webnet:
